name = "Dummy1"
uuid = "f7bc0a32-b501-410f-a5e3-5d2b3b8c0e6f"
authors = ["Simon Avery <savery@ieee.org> and contributors"]
version = "1.0.1"

[deps]
Dummy3 = "a15f9a99-31c9-401d-87e4-3fe0ccb07a31"
Dummy2 = "fb23cc6c-415b-4b10-a7ae-91d1f24ce4a7"

[compat]
julia = "1"
Dummy2 = "1"
Dummy3 = "1"


[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
