name = "Dummy1"
uuid = "f7bc0a32-b501-410f-a5e3-5d2b3b8c0e6f"
authors = ["Simon Avery <savery@ieee.org> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
